# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27a17a82c27178fd5ff367fc3b28626e63c7a278fa115da7de1cce0b9b07e3e9c5f6b026265a9ebcf203137574f5f0458fdfb91a4bcea1a3c452fbd3bd0ca98

test:
  secret_key_base: a7def73f96fae3d1651f62e661a03a31f878c503b3583d8a7b2815b32f85443eded7c7310549568af0e098b7b35a79784cab1b25fc6cc6e0fe88808e2c99afce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
